# Generated by Django 5.1 on 2024-09-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
